jobs:
  - name: sampletest-release
    type: release
    steps:
      - IN: sampletest-version
      - IN: sampletest-manifest
      - TASK: managed
        bump: minor
        
  - name: sampletest-manifest
    type: manifest
    steps:
      - IN: sampletest-image1
        versionNumber: 6
      - TASK: managed
      - IN: triggertestsample1
    flags:
      - sampletest-manifest
      
  - name: sampletest-ecsdeploy
    type: deploy
    steps:
      - IN: sampletest-manifest
      - IN: sampletest-cluster
      #- TASK: managed
        #deployMethod: upgrade
